import {
  Calendar,
  Sun,
  MoonStar,
  Check,
  ChevronDown,
  ChevronUp,
  Phone,
  ArrowRight,
  MoveRight,
  Cat,
  Circle,
  Diamond,
  Egg,
  Hexagon,
  Moon,
  Octagon,
  Pill,
  Scan,
  ScanLine,
  Stethoscope,
  Beef,
  OctagonAlert,
  TriangleAlert,
  FileWarning,
  ChefHat,
} from "lucide-react-native";
import { iconWithClassName } from "./iconWithClassName";
iconWithClassName(Cat);
iconWithClassName(Circle);
iconWithClassName(Diamond);
iconWithClassName(Egg);
iconWithClassName(Hexagon);
iconWithClassName(Moon);
iconWithClassName(Octagon);
iconWithClassName(Pill);
iconWithClassName(Scan);
iconWithClassName(ScanLine);
iconWithClassName(Stethoscope);
iconWithClassName(Calendar);
iconWithClassName(Sun);
iconWithClassName(MoonStar);
iconWithClassName(Check);
iconWithClassName(ChevronDown);
iconWithClassName(ChevronUp);
iconWithClassName(Phone);
iconWithClassName(ArrowRight);
iconWithClassName(Circle);
iconWithClassName(MoveRight);
iconWithClassName(Beef);
iconWithClassName(OctagonAlert);
iconWithClassName(TriangleAlert);
iconWithClassName(FileWarning);
iconWithClassName(ChefHat);
export {
  Sun,
  MoonStar,
  Check,
  ChevronDown,
  ChevronUp,
  Calendar,
  Phone,
  ArrowRight,
  Circle,
  MoveRight,
  Cat,
  Diamond,
  Egg,
  Hexagon,
  Moon,
  Octagon,
  Pill,
  Scan,
  ScanLine,
  Stethoscope,
  Beef,
  OctagonAlert,
  TriangleAlert,
  FileWarning,
  ChefHat,
};
